project:
  type: website
  output-dir: _site

website:
  title: "Pyodide, webR, & Quarto"
  page-navigation: true
  navbar:
    background: light
    foreground: dark
    align: right
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/coatless-talks/stats352-guest-lectures-on-dynamic-interactions-wasm
        aria-label: GitHub
  sidebar:
    - title: "Contents"
      style: "docked"
      search: true
      align: left
      contents:
        - section: "Pre-lectures"
          contents:
            - text: "1. Setup"
              href: setup-environment.qmd
        - section: "May 1st"
          contents:
            - text: "2. WebAssembly (WASM)"
              href: setup-environment.qmd
            - text: "3. Quarto"
              href: setup-environment.qmd
            - text: "4. Pyodide"
              href: setup-environment.qmd
        - section: "May 8th"
          contents:
            - text: "5. webR"
              href: setup-environment.qmd

format:
  html:
    toc: true



