project:
  type: website
  output-dir: _site

website:
  title: "Dynamic Interactions in STATS 352"
  reader-mode: true
  repo-url: https://github.com/coatless-talks/stats352-guest-lectures-on-dynamic-interactions-wasm
  repo-actions: [edit, issue]
  navbar:
    background: light
    foreground: dark
    align: right
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/coatless-talks/stats352-guest-lectures-on-dynamic-interactions-wasm
        aria-label: GitHub
  sidebar:
    style: "floating"
    search: true
    contents: 
      - section: "May 1st"
        contents:
          - text: "1. WebAssembly (WASM)"
            href: day01a-wasm.qmd
          - text: "2. Quarto"
            href: day01b-quarto.qmd
      - section: "May 8th"
        contents:
          - text: "3. Create and Publish"
            href: day02a-create-and-publish-rstudio.qmd
          - text: "4. Convert"
            href: day02b-convert.qmd
#          - text: "5. Slides"
#            href: day02c-slides.qmd
          - text: "5. Currency"
            href: day02d-currency.qmd
