project:
  type: website

website:
  title: "webR, Pyodide, & Quarto Series"
  navbar:
    left:
      - href: readme.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



